### ISSUE TITLE
Problem with Spotify being the resource for images

### ISSUE THREAD

**Issue by lorddah** [lucienimmink/JSMusicDB2#5]
I'm not sure what prompted this change but I don't find this very efficient.
A good example would be the "Garden State" OST with the cover of "A State of Trance":
![image](https://cloud.githubusercontent.com/assets/8916934/5492258/3ac6b894-86e0-11e4-8ea4-80c5efdb8e12.png)
Do you think you could make this optional so that people like me that already have covers for all their albums actually get the proper ones?

(note that with the former implementation not all covers were loaded but I never took the time to try and find out why)

Cheers.

**Comment by lucienimmink** [comment]
You can now switch back to last.fm only images in the settings.
